### ISSUE TITLE
Client Members

### ISSUE THREAD

**Issue by Peter-Scheelke** [sh4ne/Scrabble_CS3450#33]
![image](https://cloud.githubusercontent.com/assets/15118063/10930723/1d5c3f28-827e-11e5-9a98-14e0b57d487a.png)
Create the data members of the client class.

**Comment by joshcv2112** [comment]
Is the gameObjects member a list of type "Object". If not, what should it's data type be? Also, isn't GameWorld (for the member variable gameWorld) a namespace, and not a data type (class)? @sh4ne @Peter-Scheelke
